version: '3.8'

services:
  strapi:
    build: .
    ports:
      - "1337:1337"
    volumes:
      - ./src:/app/src
      - ./.tmp:/app/.tmp
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=1337
      - APP_KEYS=yzQvSsB7XhbvBQKGrF2MtQ==,3p6vWuo33m3WJ2mJXvRyPA==,FXnqC045XsPoV9ofAX1mdQ==,IgGTzeB/67sctb4Btw6J4Q==
      - API_TOKEN_SALT=vbcKcwi5vFjcYQBmzLA4NQ==
      - ADMIN_JWT_SECRET=8bd/tPCvHer8RhFPgTy5Sg==
      - TRANSFER_TOKEN_SALT=5ikgINQzpV3qlhLSiTAj2g==
      - ENCRYPTION_KEY=KEjxQqCyTF3XjWNYNidXVw==
    restart: unless-stopped